version: "3.3"

services:
  category-service:
    build: ./category-service
    ports:
      - "6053:6053"
  product-service:
    build: ./product-service
    ports:
      - "7053:7053"
  postgres-ps:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data